'use client';

import React from 'react';
import Image from 'next/image';
import { ModalType } from '@/types';

interface FooterProps {
  onOpenModal: (type: ModalType) => void;
  domainName: string;
}

export default function Footer({ onOpenModal, domainName }: FooterProps) {
  return (
    <footer className="w-full bg-[#060b13] border-t border-white/5 py-10 px-4 mt-auto relative z-10">
      <div className="max-w-7xl mx-auto w-full space-y-8">
        
        {/* Warning notification banner */}
        <div className="bg-[#111823]/80 border border-amber-500/10 p-5 rounded-2xl">
          <p className="text-xs md:text-sm text-slate-400 font-medium leading-relaxed text-center">
            <span className="text-[#ef8c16] font-extrabold uppercase mr-1">Player Warning:</span>
            Players are requested not to contact any untrusted sources for <span className="text-white font-bold">{domainName}</span> accounts as this is an online site and they can only register independently without any agents. Only deposit through the account details generated by the system or provided by our official support team.
          </p>
        </div>

        {/* Operating status & domain title */}
        <div className="text-center space-y-1">
          <h3 className="text-sm md:text-base font-extrabold text-slate-300 tracking-wider uppercase">
            This site is operated by <span className="text-gold-gradient font-black">{domainName}</span>
          </h3>
          <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">
            © {new Date().getFullYear()} {domainName} All rights reserved.
          </p>
        </div>

        {/* Horizontal divider line */}
        <div className="w-full flex items-center justify-center">
          <div className="w-full max-w-lg h-[1px] bg-gradient-to-r from-transparent via-white/10 to-transparent"></div>
        </div>

        {/* Policy modals links navbar */}
        <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-3 text-xs md:text-sm font-bold">
          <button
            onClick={() => onOpenModal('terms')}
            className="text-slate-400 hover:text-[#ef8c16] transition cursor-pointer"
          >
            Terms &amp; Conditions
          </button>
          <span className="w-1 h-1 rounded-full bg-white/20 hidden md:inline"></span>
          <button
            onClick={() => onOpenModal('about')}
            className="text-slate-400 hover:text-[#ef8c16] transition cursor-pointer"
          >
            About Us
          </button>
          <span className="w-1 h-1 rounded-full bg-white/20 hidden md:inline"></span>
          <button
            onClick={() => onOpenModal('responsible')}
            className="text-slate-400 hover:text-[#ef8c16] transition cursor-pointer"
          >
            Responsible Gaming
          </button>
          <span className="w-1 h-1 rounded-full bg-white/20 hidden md:inline"></span>
          <button
            onClick={() => onOpenModal('privacy')}
            className="text-slate-400 hover:text-[#ef8c16] transition cursor-pointer"
          >
            Privacy Policy
          </button>
          <span className="w-1 h-1 rounded-full bg-white/20 hidden md:inline"></span>
          <button
            onClick={() => onOpenModal('rules')}
            className="text-slate-400 hover:text-[#ef8c16] transition cursor-pointer"
          >
            Rules
          </button>
        </div>

        {/* Compliance logos */}
        <div className="flex items-center justify-center gap-8 pt-4">
          <div className="w-[45px] h-[45px] relative">
            <Image
              src="/assets/18-plus-Cp43T1dJ.webp"
              alt="18+"
              fill
              className="object-contain opacity-70 hover:opacity-100 transition"
              loading="lazy"
            />
          </div>
          <div className="w-[120px] h-[30px] relative">
            <Image
              src="/assets/betfair-jHqPhuAV.webp"
              alt="Betfair Compliance"
              fill
              className="object-contain opacity-70 hover:opacity-100 transition"
              loading="lazy"
            />
          </div>
        </div>

      </div>
    </footer>
  );
}
